import type { OfferType } from '@/types';

export const fakeOffers: OfferType[] = [
  {
    id: 1,
    propertyName: 'Dome in La Mesa',
    hostName: 'Kaiya Culhane',
    beds: 3,
    baths: 2,
    area: 0,
    price: 198,
    originalPrice: 752,
    rating: 4.92,
    ratingCount: 541,
    status: 'vacant',
    imageUrl: '/assets/images/fake-properties/owners/1.png',
    airbnbUrl: '',
    requestId: 110,
    createdAt: '2023/12/31',
    updatedAt: '2023/12/31',
    address: 'Squirrel Hill Borth 91791',
  },
  {
    id: 2,
    propertyName: 'Dome in La Mesa',
    hostName: 'Kaiya Culhane',
    beds: 3,
    baths: 2,
    area: 0,
    price: 198,
    originalPrice: 852,
    rating: 4.92,
    ratingCount: 541,
    status: 'vacant',
    imageUrl: '/assets/images/fake-properties/owners/1.png',
    airbnbUrl: '',
    requestId: 110,
    createdAt: '2023/12/31',
    updatedAt: '2023/12/31',
    address: 'Squirrel Hill Borth 91791',
  },
  {
    id: 3,
    propertyName: 'Dome in La Mesa',
    hostName: 'Kaiya Culhane',
    beds: 3,
    baths: 2,
    area: 0,
    price: 198,
    originalPrice: 652,
    rating: 4.92,
    ratingCount: 541,
    status: 'vacant',
    imageUrl: '/assets/images/fake-properties/owners/1.png',
    airbnbUrl: '',
    requestId: 110,
    createdAt: '2023/12/31',
    updatedAt: '2023/12/31',
    address: 'Squirrel Hill Borth 91791',
  },
  {
    id: 4,
    propertyName: 'Dome in La Mesa',
    hostName: 'Kaiya Culhane',
    beds: 3,
    baths: 2,
    area: 0,
    price: 198,
    originalPrice: 552,
    rating: 4.92,
    ratingCount: 541,
    status: 'vacant',
    imageUrl: '/assets/images/fake-properties/owners/1.png',
    airbnbUrl: '',
    requestId: 110,
    createdAt: '2023/12/31',
    updatedAt: '2023/12/31',
    address: 'Squirrel Hill Borth 91791',
  },
];
