import type { OfferDetailType, OfferType } from "@/types";

export const fakeOffers: OfferType[] = [
  {
    id: 1,
    propertyName: "Dome in La Mesa",
    hostName: "Kaiya Culhane",
    beds: 3,
    baths: 2,
    area: 0,
    price: 198,
    originalPrice: 752,
    rating: 4.92,
    ratingCount: 541,
    status: "vacant",
    imageUrl: "/assets/images/fake-properties/owners/1.png",
    airbnbUrl: "",
    requestId: 110,
    createdAt: "2023/12/31",
    updatedAt: "2023/12/31",
    address: "Squirrel Hill Borth 91791",
  },
  {
    id: 2,
    propertyName: "Dome in La Mesa",
    hostName: "Kaiya Culhane",
    beds: 3,
    baths: 2,
    area: 0,
    price: 198,
    originalPrice: 852,
    rating: 4.92,
    ratingCount: 541,
    status: "vacant",
    imageUrl: "/assets/images/fake-properties/owners/1.png",
    airbnbUrl: "",
    requestId: 110,
    createdAt: "2023/12/31",
    updatedAt: "2023/12/31",
    address: "Squirrel Hill Borth 91791",
  },
  {
    id: 3,
    propertyName: "Dome in La Mesa",
    hostName: "Kaiya Culhane",
    beds: 3,
    baths: 2,
    area: 0,
    price: 198,
    originalPrice: 652,
    rating: 4.92,
    ratingCount: 541,
    status: "vacant",
    imageUrl: "/assets/images/fake-properties/owners/1.png",
    airbnbUrl: "",
    requestId: 110,
    createdAt: "2023/12/31",
    updatedAt: "2023/12/31",
    address: "Squirrel Hill Borth 91791",
  },
  {
    id: 4,
    propertyName: "Dome in La Mesa",
    hostName: "Kaiya Culhane",
    beds: 3,
    baths: 2,
    area: 0,
    price: 198,
    originalPrice: 552,
    rating: 4.92,
    ratingCount: 541,
    status: "vacant",
    imageUrl: "/assets/images/fake-properties/owners/1.png",
    airbnbUrl: "",
    requestId: 110,
    createdAt: "2023/12/31",
    updatedAt: "2023/12/31",
    address: "Squirrel Hill Borth 91791",
  },
];

export const fakeDetailOffers: OfferDetailType = {
  propertyName: "Dome in La Mesa",
  hostName: "Kaiya Culhane",
  price: 198,
  originalPrice: 452,
  imageUrls: [
    "/assets/images/fake-properties/1.png",
    "/assets/images/fake-properties/2.png",
    "/assets/images/fake-properties/3.png",
    "/assets/images/fake-properties/1.png",
    "/assets/images/fake-properties/2.png",
  ],
  avatar: "assets/images/fake-properties/owners/1.png",
  reviewCount: 60,
  verified: true,
  superHost: true,
  hostEmail: "host@gmail.com",
  propertyDescription:
    "Lorem ipsum dolor sit amet. Sed repellat odio ut molestiae natus id galisum dignissimos ex ipsa aliquam. Est unde delectus et repellendus magnam est delectus excepturi non repellat under vbiif igifb fihiaskbfgsiabifgc bigidsgfsdgf nfidshf hiqwbifghowe fowhkcbw id galisum dignissimos ex ipsa aliquam. Est unde delectus et repellendus magnam est delectus excepturi non repellat under vbiif igifb fihiaskbfgsia.",
  guestReviews: null,
  checkIn: "8/13/23",
  checkOut: "8/16/23",
  guests: 2,
  amenites: [
    {
      type: "Baths",
      count: 1,
    },
    {
      type: "Beds",
      count: 1,
    },
    {
      type: "Baths",
      count: 1,
    },
    {
      type: "Beds",
      count: 1,
    },
    {
      type: "Ocean",
    },
    {
      type: "Ocean",
    },
    {
      type: "Ocean",
    },
    {
      type: "Ocean",
    },
  ],
  requestId: 110,
};
