version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.5.0
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm package cache
          key: v1-cache-dependencies-{{ checksum "frontend/pnpm-lock.yaml" }}-{{ arch }}
      - run:
          name: Install pnpm
          command: npm install -g pnpm
      - run:
          name: Install dependencies
          command: cd frontend && pnpm install
      - save_cache:
          name: Save pnpm package cache
          paths:
            - '~/.pnpm-store'
          key: v1-cache-dependencies-{{ checksum "frontend/pnpm-lock.yaml" }}-{{ arch }}
      # - run:
      #     name: Build
      #     command: cd frontend && pnpm run build
      - run:
          name: Lint
          command: cd frontend && pnpm run lint
