export const ALL_PROPERTY_AMENITIES = [
  "Bathtub",
  "Hair dryer",
  "Hot water",
  "Shampoo",
  "Essentials",
  "Bed linens",
  "Dryer",
  "Dryer in common space",
  "Extra pillows and blankets",
  "Hangers",
  "Iron",
  "Room-darkening shades",
  "Safe",
  "Towels provided",
  "Washer",
  "Washer in common space",
  "Cable TV",
  "Dvd player",
  "Game console",
  "Stereo system",
  "TV",
  "Baby bath",
  "Baby monitor",
  "Babysitter recommendations",
  "Children’s books and toys",
  "Changing table",
  "Children’s dinnerware",
  "Crib",
  "Family/kid friendly",
  "Fireplace guards",
  "High chair",
  "Outlet covers",
  "Pack ’n Play/travel crib",
  "Stair gates",
  "Table corner guards",
  "Window guards",
  "Air conditioning",
  "Heating",
  "Indoor fireplace",
  "Carbon monoxide detector",
  "Emergency exit",
  "Fire extinguisher",
  "First aid kit",
  "Smoke detector",
  "Desk",
  "Internet",
  "Laptop friendly workspace",
  "Pocket wifi",
  "Wireless Internet",
  "Coffee maker",
  "Cookware",
  "Dishes and silverware",
  "Dishwasher",
  "Kitchen",
  "Kettle",
  "Microwave",
  "Oven",
  "Refrigerator",
  "Stove",
  "Toaster",
  "Beach",
  "Beach Front",
  "Beach View",
  "Downtown",
  "Golf course front",
  "Golf view",
  "Lake",
  "Lake access",
  "Lake Front",
  "Mountain",
  "Mountain view",
  "Near Ocean",
  "Ocean Front",
  "Resort",
  "River",
  "Rural",
  "Sea view",
  "Ski In",
  "Ski in/Ski out",
  "Ski Out",
  "Town",
  "Village",
  "Water View",
  "Waterfront",
  "Outdoor pool",
  "Garden or backyard",
  "Bicycles available",
  "Patio or balcony",
  "BBQ grill",
  "Beach essentials",
  "Elevator",
  "Free parking on premises",
  "Indoor pool",
  "Hot tub",
  "Gym",
  "Swimming pool",
  "Communal pool",
  "Free parking on street",
  "EV charger",
  "Single level home",
  "Private pool",
  "Paid parking off premises",
  "Breakfast",
  "Long term stays allowed",
  "Luggage dropoff allowed",
  "High touch surfaces disinfected",
  "Enhanced cleaning practices",
  "Doorman",
  "Cleaning Disinfection",
  "Cleaning before checkout",
  "Grab-rails for shower and toilet",
  "Tub with shower bench",
  "Wheelchair accessible",
  "Wide clearance to bed",
  "Wide clearance to shower and toilet",
  "Wide hallway clearance",
  "Accessible-height toilet",
  "Accessible-height bed",
  "Paid parking on premises",
  "Outdoor dining area",
  "Pool table",
  "Piano",
  "Exercise equipment",
  "Fire pit",
  "Outdoor shower",
] as const;
