export const ALL_CITIES = [
  "Black Hawk, United States of America",
  "Arvada, United States of America",
  "Eagle, United States",
  "Bennington, United States of America",
  "College Place, United States",
  "Lee's Summit, United States of America",
  "Mountain View, United States",
  "Banner Elk, United States",
  "Charlotte, United States",
  "Eureka Springs, United States",
  "Houston, United States of America",
  "Oceanside, United States",
  "Hilton Head Island, United States",
  "Gordonsville, United States",
  "San Jose, United States",
  "Fort Walton Beach, United States",
  "West Hollywood, United States",
  "Park City, United States",
  "Greenbelt, United States",
  "Poway, United States",
  "Dallas, United States",
  "Mexico City, Mexico",
  "Buenos Aires, Argentina",
  "Palm Desert, United States",
  "Tahoe City, United States",
  "Boise, United States of America",
  "Naples, United States",
  "Fenton Township, United States of America",
  "Rancho Mirage, United States",
  "Barcelona, Spain",
  "North Canton, United States",
  "Palm Coast, United States",
  "Destin, United States",
  "DeSoto, United States of America",
  "Cabo Bello, Mexico",
  "West Palm Beach, United States",
  "Ruskin, United States of America",
  "Shady Shores, United States of America",
  "Mount Laguna, United States",
  "Oakland Park, United States",
  "Saugus, United States",
  "Denver, United States of America",
  "Chía, Colombia",
  "Cameron County, United States",
  "Malibu, United States",
  "South Padre Island, United States of America",
  "Galveston, United States of America",
  "Canyon Lake, United States",
  "Isle of Palms, United States",
  "Irving, United States",
  "Blue Ridge, United States of America",
  "Marbella, Spain",
  "Alexandria, United States",
  "Burien, United States",
  "Grayland, United States",
  "Los Altos Hills, United States",
  "Edisto Island, United States",
  "Baraboo, United States",
  "Austin, United States",
  "Boynton Beach, United States",
  "Emerald Hills, United States",
  "Sevierville, United States",
  "Blue Springs, United States",
  "Anaheim, United States",
  "Farmers Branch, United States",
  "Shelton, United States",
  "Twin Falls, United States",
  "Southside, U.S. Virgin Islands",
  "Kalama, United States",
  "Conway, United States",
  "Harrisonville, United States of America",
  "Harlingen, United States",
  "Lluchmayor, Spain",
  "Panama City Beach, United States",
  "National City, United States",
  "Carnelian Bay, United States",
  "Pigeon Forge, United States",
  "Wilton Manors, United States of America",
  "Carmel-by-the-Sea, United States",
  "Carrollton, United States",
  "Oakland, United States",
  "Cedar Park, United States",
  "Paris, France",
  "Cugulutx, Spain",
  "Federal Way, United States",
  "Fort Lauderdale, United States",
  "Raytown, United States",
  "Kirkland, United States",
  "Garland, United States",
  "Westminster, United States",
  "Punta Cana, Dominican Republic",
  "Key West, United States",
  "Boyne Falls, United States",
  "Austin, United States of America",
  "Berkeley, United States of America",
  "Henderson, United States",
  "Port Orford, United States",
  "Bothell, United States",
  "West Windsor, United States",
  "Arlington, United States of America",
  "Los Angeles, United States of America",
  "Fort Lauderdale, United States of America",
  "Birmingham, United States",
  "Fremont, United States",
  "Grand Prairie, United States of America",
  "Snowmass Village, United States",
  "Riverside, United States",
  "Clarkesville, United States",
  "Redondo Beach, United States",
  "Reunion, United States",
  "New Orleans, United States",
  "Santiago, Chile",
  "Long Beach, United States",
  "Auburn, United States",
  "North Richland Hills, United States",
  "Coronado, United States",
  "Safety Harbor, United States",
  "Truckee, United States",
  "McArthur, United States",
  "Lauderdale-by-the-Sea, United States",
  "Issaquah, United States",
  "Lake Buena Vista, United States",
  "Kihei, United States",
  "Solana Beach, United States",
  "Palm Springs, United States",
  "West Sacramento, United States",
  "Boston, United States",
  "Zephyr Cove, United States",
  "Branson West, United States",
  "Tacoma, United States of America",
  "Arlington, USA",
  "Stateline, United States",
  "Aurora, United States",
  "Kansas City, United States of America",
  "South Lake Tahoe, United States",
  "Phoenix, United States",
  "Nashville, United States",
  "Port St. Lucie, United States",
  "Breckenridge, United States",
  "Reunion, USA",
  "Kissimmee, United States",
  "Harlingen, United States of America",
  "Rockaway Beach, United States",
  "SeaTac, United States",
  "Keystone, United States",
  "Grand Lake, United States",
  "Washington DC, United States",
  "Seattle, United States of America",
  "Winchester, United States of America",
  "North Bend, United States",
  "Oakland, United States of America",
  "St. Augustine, United States of America",
  "Denver, United States",
  "Ponte Vedra Beach, United States",
  "Williamsburg, United States",
  "Sachse, United States",
  "Kabupaten Badung, Indonesia",
  "Philadelphia, United States",
  "Evergreen, United States",
  "Oxon Hill, United States",
  "Stock Island, United States",
  "Daytona Beach Shores, United States",
  "Conroe, United States",
  "Commerce City, United States",
  "São Paulo, Brazil",
  "Ormond Beach, United States",
  "Rowlett, United States",
  "Summerland Key, United States",
  "Gresham, United States",
  "Garibaldi, United States",
  "Plymouth, United States",
  "Sullivan's Island, United States",
  "Carlsbad, United States",
  "Golden, United States",
  "Ridgedale, United States",
  "St. Pete Beach, United States",
  "Sarasota, United States",
  "Tamarindo, Costa Rica",
  "Mystic, United States",
  "Cascade-Chipita Park, United States",
  "Clearwater, United States",
  "Panama City, Panama",
  "SeaTac, United States of America",
  "Hershey, United States",
  "Redington Beach, United States",
  "Scottsdale, United States of America",
  "Kitty Hawk, United States",
  "Denton, United States",
  "DeSoto, United States",
  "Joshua Tree, United States of America",
  "Broken Bow, United States",
  "Edmond, United States of America",
  "San Antonio, United States",
  "Surfers Paradise, Australia",
  "Longbranch, United States",
  "undefined, Thailand",
  "Hollister, United States",
  "Lakeside, United States",
  "Indio, United States",
  "Escondido, United States",
  "Villa Rica, United States",
  "Spring City, United States of America",
  "San Diego, United States",
  "Aspen Highlands, United States",
  "Anniston, United States",
  "Vancouver, United States",
  "Koloa, United States",
  "Sheridan, United States",
  "Bonita, United States",
  "Englewood, United States",
  "Lake Geneva, United States",
  "San Mateo, United States",
  "Cardiff, United States",
  "Boise, United States",
  "Davenport, United States",
  "Malden, United States",
  "Santa Rosa Beach, United States of America",
  "Tambon Mai Khao, Thailand",
  "Corolla, United States",
  "Clermont, United States",
  "Venice, US",
  "Knoxville, United States",
  "Pagosa Springs, United States",
  "Avon, United States",
  "Peyton, United States of America",
  "Thompson's Station, United States",
  "St. Petersburg, United States",
  "Yucca Valley, United States",
  "Cape Canaveral, United States",
  "Idaho Springs, United States",
  "London, United Kingdom",
  "Salt Lake City, United States",
  "Pompano Beach, United States",
  "Aspen, United States",
  "Platte Woods, United States",
  "Monument, United States of America",
  "Palo Alto, United States",
  "National City, United States of America",
  "Indian Rocks Beach, United States",
  "La Jolla, United States",
  "Coos Bay, United States",
  "Flagstaff, United States",
  "Menlo Park, United States",
  "Tempe, United States",
  "Thompson's Station, United States of America",
  "Seattle, United States",
  "Mesquite, United States",
  "Wilton Manors, United States",
  "Mercer Island, United States",
  "Apple Valley, United States",
  "Treasure Island, United States",
  "La Mesa, United States",
  "Nags Head, United States",
  "Flagstaff, United States of America",
  "Madrid, Spain",
  "Evergreen, United States of America",
  "Las Vegas, United States",
  "Encinitas, United States",
  "Excelsior Springs, United States",
  "Mill Valley, United States",
  "Scottsdale, United States",
  "Falmouth, United States",
  "Mountlake Terrace, United States of America",
  "Memphis, United States",
  "Wheat Ridge, United States",
  "Meridian, United States",
  "Grand Prairie, United States",
  "Steamboat Springs, United States",
  "Keaau, United States",
  "The Colony, United States",
  "Cave Creek, United States",
  "Rockaway Beach, United States of America",
  "Arvada, United States",
  "Atlanta, United States",
  "Daytona Beach, United States",
  "U.S. Virgin Islands, U.S. Virgin Islands",
  "Gatlinburg, United States",
  "Río Grande, Puerto Rico",
  "Lahaina, United States",
  "Santee, United States",
  "Lilliwaup, United States",
  "Kennett Square, United States",
  "Portland, United States",
  "North Charleston, United States",
  "San Francisco, United States",
  "Port Aransas, United States",
  "Pittsburgh, United States",
  "Mount Pleasant, United States",
  "Telluride, United States",
  "Ventura, United States",
  "Shoreline, United States",
  "Harrisonville, United States",
  "Meridian, United States of America",
  "Apple Valley, United States of America",
  "Four Corners, United States",
  "Columbia, United States",
  "Tampa, United States",
  "North Las Vegas, United States",
  "Redmond, United States",
  "Holiday Island, United States",
  "Branson, United States",
  "Wolfeboro, United States",
  "Lighthouse Point, United States",
  "Orlando, United States",
  "Birmingham, United States of America",
  "Nashville, United States of America",
  "Oakland Park, United States of America",
  "Rio de Janeiro, Brazil",
  "Houston, United States",
  "Aledo, United States of America",
  "Plano, United States",
  "La Feria, United States",
  "Charleston, United States",
  "Haltom City, United States",
  "Newport, United States",
  "Lynnwood, United States",
  "Coachella, United States",
  "Norcross, United States",
  "St. Augustine, United States",
  "Joshua Tree, United States",
  "Rancho Santa Fe, United States",
  "Miami, United States",
  "Tulsa, United States of America",
  "Myrtle Beach, United States",
  "North Myrtle Beach, United States",
  "Sammamish, United States",
  "La Quinta, United States",
  "Deerfield Beach, United States",
  "Washington, United States",
  "Nantucket, United States",
  "Albany County, United States",
  "Napa, United States",
  "Colorado Springs, United States",
  "Imperial Beach, United States",
  "Nassau, The Bahamas",
  "Peabody, United States",
  "Marco Island, United States",
  "De Soto, United States",
  "Sarasota, United States of America",
  "Lincoln, United States",
  "Renton, United States",
  "Cambridge, United States",
  "Arlington, United States",
  "San Diego, United States of America",
  "Los Altos, United States",
  "Noord, Aruba",
  "Wailea-Makena, United States",
  "Reading, United States",
  "Fort Myers, United States",
  "Peoria, United States",
  "Woodinville, United States",
  "Hoodsport, United States",
  "Vail, United States",
  "Granby, United States of America",
  "Poulsbo, United States",
  "Cashiers, United States",
  "Bozeman, United States",
  "Tabernash, United States",
  "Dana Point, United States",
  "Beaverton, United States",
  "Little Elm, United States",
  "Sedona, United States",
  "Independence, United States",
  "Jersey Village, United States",
  "Mesa, United States",
  "Brookline, United States",
  "Berryville, United States",
  "Kansas City, United States",
  "Durango, United States",
  "Lake Arrowhead, United States",
  "Bailey, United States",
  "Silver Spring, United States",
  "Fairfax, United States",
  "undefined, United States",
  "San José del Cabo, Mexico",
  "Nampa, United States",
  "Los Angeles, United States",
  "Woburn, United States",
  "Topanga, United States",
  "Cottonwood, United States",
  "Miramar Beach, United States",
  "Phoenix, United States of America",
  "Silverthorne, United States",
  "Beverly Hills, United States",
  "Glendale, United States",
  "San Diego, USA",
  "Bellevue, United States",
  "Broken Bow, United States of America",
  "Sacramento, United States",
];
