import { api } from "@/utils/api";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Success: NextPage = () => {
  const router = useRouter();
  const sessionId = useRouter().query.session_id as string;

  const { data } = api.stripe.getStripeSession.useQuery(
    { sessionId },
    {
      enabled: router.isReady,
    },
  );

  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        Email Linked: {data?.email}
      </main>
    </>
  );
};

export default Success;
