import { api } from "@/utils/api";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Success: NextPage = () => {
  const router = useRouter();
  const sessionId = useRouter().query.session_id as string;
  const [description, setDescription] = useState("");
  const [email, setEmail] = useState("");

  const session = api.stripe.getStripeSession.useQuery(
    { sessionId },
    {
      enabled: router.isReady,
    },
  );

  useEffect(() => {
    if (session.data?.email && session.data?.description) {
      setEmail(session.data?.email);
      setDescription(session.data?.description);
    }
  }, [session.data, router]);

  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        Validating payment...
        <h1>Email</h1>
        <p>{email}</p>
        <h1>Description</h1>
        <p>{description}</p>
      </main>
    </>
  );
};

export default Success;
